import getCssSelector from "css-selector-generator";
import { finder } from "@medv/finder";
import { ScriptMsg } from "../scriptMsg.constants";

export const getGenerationAttributes = () => {
  /*
        Software License Agreement (BSD License)

        Copyright (c) 2009, Mozilla Foundation
        All rights reserved.

        Redistribution and use of this software in source and binary forms, with or without modification,
        are permitted provided that the following conditions are met:

        * Redistributions of source code must retain the above
          copyright notice, this list of conditions and the
          following disclaimer.

        * Redistributions in binary form must reproduce the above
          copyright notice, this list of conditions and the
          following disclaimer in the documentation and/or other
          materials provided with the distribution.

        * Neither the name of Mozilla Foundation nor the names of its
          contributors may be used to endorse or promote products
          derived from this software without specific prior
          written permission of Mozilla Foundation.

        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
        IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
        FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
        CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
        DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
        IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
        OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
        -->
        */
  const getElementTreeXPath = (element) => {
    const paths = [];

    // Use nodeName (instead of localName) so namespace prefix is included (if any).
    for (; element && element.nodeType == Node.ELEMENT_NODE; element = element.parentNode) {
      let index = 0;
      let hasFollowingSiblings = false;
      for (let sibling = element.previousSibling; sibling; sibling = sibling.previousSibling) {
        // Ignore document type declaration.
        if (sibling.nodeType == Node.DOCUMENT_TYPE_NODE) continue;

        if (sibling.nodeName == element.nodeName) ++index;
      }

      for (let sibling = element.nextSibling; sibling && !hasFollowingSiblings; sibling = sibling.nextSibling) {
        if (sibling.nodeName == element.nodeName) {
          hasFollowingSiblings = true;
        }
      }

      const tagName = (element.prefix ? element.prefix + ":" : "") + element.localName;
      const pathIndex = index || hasFollowingSiblings ? "[" + (index + 1) + "]" : "";
      paths.splice(0, 0, tagName + pathIndex);
    }

    return paths.length ? "/" + paths.join("/") : null;
    /*
            <---
            */
  };

  const generateSelectorByElement = (element) => {
    let selectorByGenerator;
    let selectorByFinder;

    // Due to finder lib issue, we have to catch errors.
    // If css selector generated by finder contains ".", for example #Country_16856319000360.6264611129794591
    // We get "Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document':
    // '#Country_16856319000360.6264611129794591' is not a valid selector."
    // And because of lib logic we can't prevent generation these selectors.
    // Reproduced on https://www.docker.com
    try {
      const finderForbiddenAttributes = ["jdn-hash", "href", "class", "xmlns", "xmlns:xlink", "xlink:href"];
      selectorByFinder = finder(element, {
        attr: (name, value) => value && !finderForbiddenAttributes.includes(name),
      });
    } catch (err) {
      __DEV_ENVIRONMENT__ && console.log(err);
      selectorByFinder = err;
    }

    // If "id" attribute starts with number, for example id="6264611129794591"
    // We get "Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document':
    // '#6264611129794591' is not a valid selector."
    // And because of lib logic we can't prevent generation these selectors.
    // Reproduced on https://www.otto.de
    const generatorOptions = {
      blacklist: [/jdn-hash/, /href/],
      maxCombinations: 30,
      maxCandidates: 30,
    };

    try {
      selectorByGenerator = getCssSelector(element, generatorOptions);
    } catch (err) {
      __DEV_ENVIRONMENT__ && console.log(err);
      selectorByGenerator = err;
    }

    const isSelectorByGeneratorString = typeof selectorByGenerator === "string";
    const isSelectorByFinderString = typeof selectorByFinder === "string";

    if (isSelectorByGeneratorString && isSelectorByFinderString) {
      const selector = selectorByGenerator.length < selectorByFinder.length ? selectorByGenerator : selectorByFinder;
      return selector;
    } else if (!isSelectorByFinderString && isSelectorByGeneratorString) {
      return selectorByGenerator;
    } else if (!isSelectorByGeneratorString && isSelectorByFinderString) {
      return selectorByFinder;
    } else {
      return "CSS selector generation was failed";
    }
  };

  const generateSelectorByHash = ({ element_id, jdnHash }) => {
    const element = document.querySelector(`[jdn-hash='${jdnHash}']`);
    return element ? { element_id, cssSelector: generateSelectorByElement(element) } : null;
  };

  /*
    Make an 'ID' attribute to the camel notation. Rules:
    - Replace the dash just before the letters (search-button -> searchButton)
    - Before the numbers, replace a dash into an underline (ma-0-6 -> ma_0_6)
    - Otherwise, leave it as it is (searchButton -> searchButton)
  */
  const camelCase = (string) => {
    if (string.indexOf("-") < 0 && string.indexOf("_") < 0) {
      return string;
    }
    const regex = /(_|-)([a-z])/g;
    const toCamelCase = (string) => string[1].toUpperCase();
    return string.toLowerCase().replace(regex, toCamelCase).replaceAll("-", "_");
  };

  const mapElements = (elements) => {
    const generationAttributes = elements
      .map((predictedElement) => {
        const element = document.querySelector(`[jdn-hash='${predictedElement.jdnHash}']`);
        if (!element) {
          return;
        }
        const attrName = element.getAttribute("name");
        predictedElement.elemName = attrName ? camelCase(attrName) : "";
        predictedElement.elemId = element.id && typeof element.id === "string" ? camelCase(element.id) : "";
        predictedElement.elemText = element.textContent;
        predictedElement.elemAriaLabel = element.getAttribute("aria-label");
        predictedElement.locator = {
          xPath: getElementTreeXPath(element),
          cssSelector: generateSelectorByElement(element),
        };

        return {
          ...predictedElement,
        };
      })
      .filter((el) => !!el);
    return generationAttributes;
  };

  chrome.runtime.onMessage.addListener(({ message, param }, sender, sendResponse) => {
    switch (message) {
      case ScriptMsg.GenerateAttributes:
        sendResponse(mapElements(param));
        break;
      case ScriptMsg.GetElementXpath:
        const foundElement = document.querySelector(`[jdn-hash='${param}']`);
        sendResponse(getElementTreeXPath(foundElement));
        break;
      case ScriptMsg.GenerateSelectorByHash:
        sendResponse(generateSelectorByHash(param));
        break;
      default:
        break;
    }
  });
};
