import { LocatorType } from '../../../../common/types/common';
import { LocatorTaskStatus } from '../../../../features/locators/types/locator.types';

export const locatorsTreeMock = [
  {
    depth: 0,
    searchState: undefined,
    elementId: '7967190244322359771369749968_0',
    is_shown: true,
    parent_id: '',
    jdnHash: '7967190244322359771369749968',
    locatorValue: {
      xPath: '/html/body/header/div/nav/ul[1]',
      taskStatus: LocatorTaskStatus.SUCCESS,
      errorMessage: '',
      output: '',
      cssSelector: '',
    },
    name: 'radiobuttonsUl',
    locatorType: LocatorType.xPath,
    message: '',
    predictedAttrId: '',
    predicted_label: 'radiogroup',
    pageObj: 0,
    isGenerated: true,
    tagName: 'ul',
    type: 'RadioButtons',
    isChecked: false,
    children: [
      {
        depth: 1,
        searchState: undefined,
        elementId: '3969471880322359761484771163_0',
        is_shown: true,
        parent_id: '7967190244322359771369749968',
        jdnHash: '3969471880322359761484771163',
        locatorValue: {
          xPath: '/html/body/header/div/nav/div[2]',
          taskStatus: LocatorTaskStatus.SUCCESS,
          errorMessage: '',
          output: '',
          cssSelector: '',
        },
        name: 'buttonDiv',
        locatorType: LocatorType.xPath,
        message: '',
        predictedAttrId: '',
        predicted_label: 'button',
        pageObj: 0,
        isGenerated: true,
        tagName: 'div',
        type: 'Button',
        isChecked: false,
        children: [
          {
            searchState: undefined,
            elementId: '0045220328322359764482356698_0',
            is_shown: true,
            parent_id: '3969471880322359761484771163',
            jdnHash: '0045220328322359764482356698',
            locatorValue: {
              xPath: '/html/body/header/div/nav/ul[1]/li[3]/a',
              taskStatus: LocatorTaskStatus.FAILURE,
              errorMessage: '',
              output: '',
              cssSelector: '',
            },
            name: 'textarea',
            locatorType: LocatorType.xPath,
            message: '',
            predictedAttrId: '',
            predicted_label: 'textarea-autosize',
            pageObj: 0,
            isGenerated: true,
            tagName: 'a',
            type: 'TextField',
            isChecked: false,
            children: [],
            depth: 2,
          },
          {
            elementId: '6771529534322359778589411351_0',
            is_shown: true,
            parent_id: '3969471880322359761484771163',
            jdnHash: '6771529534322359778589411351',
            locatorValue: {
              xPath: '/html/body/footer/div/div/ul',
              taskStatus: LocatorTaskStatus.STARTED,
              errorMessage: '',
              output: '',
              cssSelector: '',
            },
            name: 'listUl',
            locatorType: LocatorType.xPath,
            message: '',
            predictedAttrId: '',
            predicted_label: 'list',
            pageObj: 0,
            isGenerated: true,
            tagName: 'ul',
            type: 'List',
            isChecked: false,
            children: [],
            depth: 2,
            searchState: undefined,
          },
        ],
      },
      {
        depth: 1,
        searchState: undefined,
        elementId: '4899732051322359779677566872_0',
        is_shown: true,
        parent_id: '7967190244322359771369749968',
        jdnHash: '4899732051322359779677566872',
        locatorValue: {
          xPath: '/html/body/header/div/nav/ul[2]/li/a',
          taskStatus: LocatorTaskStatus.PENDING,
          errorMessage: '',
          output: '',
          cssSelector: '',
        },
        name: 'link',
        locatorType: LocatorType.xPath,
        message: '',
        predictedAttrId: '',
        predicted_label: 'link',
        pageObj: 0,
        isGenerated: true,
        tagName: 'a',
        type: 'Link',
        isChecked: false,
        children: [
          {
            depth: 2,
            searchState: undefined,
            elementId: '4829071593322359778594168519_0',
            is_shown: true,
            parent_id: '4899732051322359779677566872',
            jdnHash: '4829071593322359778594168519',
            locatorValue: {
              xPath: '/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[3]/ul/li[3]',
              taskStatus: LocatorTaskStatus.PENDING,
              errorMessage: '',
              output: '',
              cssSelector: '',
            },
            name: 'anyName',
            locatorType: LocatorType.xPath,
            message: '',
            predictedAttrId: '',
            predicted_label: 'breadcrumbs',
            pageObj: 0,
            isGenerated: true,
            tagName: 'li',
            type: 'Breadcrumbs',
            isChecked: false,
            children: [
              {
                depth: 3,
                searchState: undefined,
                elementId: '9636042053322359773245578788_0',
                is_shown: true,
                parent_id: '4829071593322359778594168519',
                jdnHash: '9636042053322359773245578788',
                locatorValue: {
                  xPath: '/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[5]/ul/li[5]',
                  taskStatus: LocatorTaskStatus.PENDING,
                  errorMessage: '',
                  output: '',
                  cssSelector: '',
                },
                name: 'breadcrumbsLi6',
                locatorType: LocatorType.xPath,
                message: '',
                predictedAttrId: '',
                predicted_label: 'breadcrumbs',
                pageObj: 0,
                isGenerated: true,
                tagName: 'li',
                type: 'Breadcrumbs',
                isChecked: false,
                children: [],
              },
              {
                depth: 3,
                searchState: undefined,
                elementId: '8381553594322359777170267551_0',
                is_shown: true,
                parent_id: '4829071593322359778594168519',
                jdnHash: '8381553594322359777170267551',
                locatorValue: {
                  xPath: '/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[3]/ul',
                  taskStatus: LocatorTaskStatus.PENDING,
                  errorMessage: '',
                  output: '',
                  cssSelector: '',
                },
                name: 'breadcrumbsUl',
                locatorType: LocatorType.xPath,
                message: '',
                predictedAttrId: '',
                predicted_label: 'breadcrumbs',
                pageObj: 0,
                isGenerated: true,
                tagName: 'ul',
                type: 'Breadcrumbs',
                isChecked: false,
                children: [],
              },
            ],
          },
        ],
      },
      {
        depth: 1,
        searchState: undefined,
        elementId: '4899732051322359779677566873_0',
        is_shown: true,
        parent_id: '7967190244322359771369749968',
        jdnHash: '4899732051322359779677566873',
        locatorValue: {
          xPath: '/html/body/header/div/nav/ul[2]/li/a',
          taskStatus: LocatorTaskStatus.PENDING,
          errorMessage: '',
          output: '',
          cssSelector: '',
        },
        name: 'link',
        locatorType: LocatorType.xPath,
        message: '',
        predictedAttrId: '',
        predicted_label: 'link',
        pageObj: 0,
        isGenerated: true,
        tagName: 'a',
        type: 'Link',
        isChecked: false,
        children: [
          {
            depth: 2,
            searchState: undefined,
            elementId: '4829071593322359778594168522_0',
            is_shown: true,
            parent_id: '4899732051322359779677566873',
            jdnHash: '4829071593322359778594168522',
            locatorValue: {
              xPath: '/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[3]/ul/li[3]',
              taskStatus: LocatorTaskStatus.PENDING,
              errorMessage: '',
              output: '',
              cssSelector: '',
            },
            name: 'breadcrumbsLi2',
            locatorType: LocatorType.xPath,
            message: '',
            predictedAttrId: '',
            predicted_label: 'breadcrumbs',
            pageObj: 0,
            isGenerated: true,
            tagName: 'li',
            type: 'Breadcrumbs',
            isChecked: false,
            children: [
              {
                depth: 3,
                searchState: undefined,
                elementId: '9636042053322359773245578777_0',
                is_shown: true,
                parent_id: '4829071593322359778594168522',
                jdnHash: '9636042053322359773245578777',
                locatorValue: {
                  xPath: '/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[5]/ul/li[5]',
                  taskStatus: LocatorTaskStatus.PENDING,
                  errorMessage: '',
                  output: '',
                  cssSelector: '',
                },
                name: 'breadcrumbsLi7',
                locatorType: LocatorType.xPath,
                message: '',
                predictedAttrId: '',
                predicted_label: 'breadcrumbs',
                pageObj: 0,
                isGenerated: true,
                tagName: 'li',
                type: 'Breadcrumbs',
                isChecked: false,
                children: [],
              },
              {
                depth: 3,
                searchState: undefined,
                elementId: '8381553594322359777170267550_0',
                is_shown: true,
                parent_id: '4829071593322359778594168522',
                jdnHash: '8381553594322359777170267550',
                locatorValue: {
                  xPath: '/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[3]/ul',
                  taskStatus: LocatorTaskStatus.PENDING,
                  errorMessage: '',
                  output: '',
                  cssSelector: '',
                },
                name: 'breadcrumbsUl',
                locatorType: LocatorType.xPath,
                message: '',
                predictedAttrId: '',
                predicted_label: 'breadcrumbs',
                pageObj: 0,
                isGenerated: true,
                tagName: 'ul',
                type: 'Breadcrumbs',
                isChecked: false,
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    depth: 0,
    searchState: undefined,
    elementId: '796719024432235977136974900_0',
    is_shown: true,
    parent_id: '',
    jdnHash: '796719024432235977136974900',
    locatorValue: {
      xPath: '/html/body/header/div/nav/ul[1]',
      taskStatus: LocatorTaskStatus.PENDING,
      errorMessage: '',
      output: '',
      cssSelector: '',
    },
    name: 'radiobuttonsUl',
    locatorType: LocatorType.xPath,
    message: '',
    predictedAttrId: '',
    elemText: 'radioLi7',
    predicted_label: 'radiogroup',
    pageObj: 0,
    isGenerated: true,
    tagName: 'ul',
    type: 'RadioButtons',
    isChecked: false,
    children: [],
  },
];
