import { LocatorTaskStatus } from "../../../../features/locators/types/locator.types";
import { AnnotationType, LocatorType } from "../../../../common/types/common";

export const locatorsTreeMockSearch = [
  {
    depth: 0,
    searchState: "hidden",
    element_id: "7967190244322359771369749968_0",
    parent_id: "",
    jdnHash: "7967190244322359771369749968",
    locator: {
      xPath: "/html/body/header/div/nav/ul[1]",
      cssSelector: "",
      taskStatus: LocatorTaskStatus.SUCCESS,
      errorMessage: "",
      output: "",
    },
    annotationType: AnnotationType.UI,
    locatorType: LocatorType.xPath,
    name: "radiobuttonsUl",
    message: "",
    predictedAttrId: "",
    predicted_label: "radiogroup",
    pageObj: 0,
    generate: true,
    tagName: "ul",
    type: "RadioButtons",
    children: [
      {
        depth: 2,
        searchState: "none",
        element_id: "9636042053322359773245578777_0",
        parent_id: "4829071593322359778594168522",
        jdnHash: "9636042053322359773245578777",
        locator: {
          xPath: "/html/body/div/div[1]/div/div[1]/div/div[1]/ul/li[5]/ul/li[5]",
          cssSelector: "",
          taskStatus: LocatorTaskStatus.PENDING,
          errorMessage: "",
          output: "",
        },
        annotationType: AnnotationType.UI,
        locatorType: LocatorType.xPath,
        name: "breadcrumbsLi7",
        message: "",
        predictedAttrId: "",
        predicted_label: "breadcrumbs",
        pageObj: 0,
        generate: true,
        tagName: "li",
        type: "Breadcrumbs",
        children: [],
      },
    ],
  },
  {
    depth: 0,
    searchState: "none",
    element_id: "796719024432235977136974900_0",
    parent_id: "",
    jdnHash: "796719024432235977136974900",
    locator: {
      xPath: "/html/body/header/div/nav/ul[1]",
      cssSelector: "",
      taskStatus: LocatorTaskStatus.PENDING,
      errorMessage: "",
      output: "",
    },
    annotationType: AnnotationType.UI,
    locatorType: LocatorType.xPath,
    name: "radiobuttonsUl",
    message: "",
    predictedAttrId: "",
    elemText: "radioLi7",
    predicted_label: "radiogroup",
    pageObj: 0,
    generate: true,
    tagName: "ul",
    type: "RadioButtons",
    children: [],
  },
];
