export enum HTML5classes {
  button = 'Button',
  checkbox = 'Checkbox',
  checklist = 'Checklist',
  colorpicker = 'ColorPicker',
  datalist = 'Combobox',
  datetimeselector = 'DateTimeSelector',
  dropdown = 'Dropdown',
  fileinput = 'FileInput',
  label = 'Label',
  link = 'Link',
  multidropdown = 'MultiSelector',
  multiselector = 'MultiSelector',
  numberselector = 'NumberSelector',
  progressbar = 'ProgressBar',
  radiobuttongroup = 'RadioButtons',
  range = 'Range',
  table = 'Table',
  text = 'Text',
  textarea = 'TextArea',
  textfield = 'TextField',
  title = 'Title',
  combobox = 'Combobox',
  form = 'Form',
}
