export enum MUIclasses {
  accordion = 'Accordion',
  badge = 'Badge',
  'bottom-navigation' = 'BottomNavigation',
  button = 'Button',
  'button-group' = 'ButtonGroup',
  breadcrumbs = 'Breadcrumbs',
  checkbox = 'Checkbox',
  chip = 'Chip',
  dialog = 'Dialog',
  drawer = 'Drawer',
  link = 'Link',
  list = 'List',
  menu = 'Menu',
  progress = 'ProgressBar',
  radiogroup = 'RadioButtons',
  select = 'Select',
  slider = 'Slider',
  snackbar = 'Snackbar',
  stepper = 'Stepper',
  switch = 'Switch',
  tabs = 'Tabs',
  table = 'Table',
  'textarea-autosize' = 'TextArea',
  'text-field' = 'TextField',
}
