export enum ScriptMsg {
  // app -> page messages
  AddElement = "AddElement",
  AssignDataLabel = "AssignDataLabel",
  AssignJdnHash = "AssignJdnHash",
  AssignParents = "AssignParents",
  ChangeElementName = "ChangeElementName",
  ChangeElementType = "ChangeElementType",
  ChangeStatus = "ChangeStatus",
  CheckSession = "CheckSession",
  DefineTabId = "DefineTabId",
  EvaluateXpath = "EvaluateXpath",
  EvaluateCssSelector = "EvaluateCssSelector",
  FindBySelectors = "FindBySelectors",
  GenerateAttributes = "GenerateAttributes",
  GenerateSelectorByHash = "GenerateSelectorByHash",
  GetElementXpath = "GetElementXpath",
  HighlightToggled = "HighlightToggled",
  KillHighlight = "KillHighlight",
  PingScript = "PingScript",
  SetActive = "SetActive",
  SetClosedSession = "SetClosedSession",
  SetHighlight = "SetHighlight",
  RemoveElement = "RemoveElement",
  ToggleActiveGroup = "ToggleActiveGroup",
  ToggleElement = "ToggleElement",
  ToggleDeleted = "ToggleDeleted",
  ToggleFilter = "ToggleFilter",
  UnsetActive = "UnsetActive",

  // page -> app messages
  AdvancedCalculation = "AdvancedCalculation",
  CopyLocator = "CopyLocator",
  GetActiveElements = "GetActiveElements",
  ElementSelect = "ElementSelect",
  ElementGroupSetActive = "ElementGroupSetActive",
  ElementGroupUnsetActive = "ElementGroupUnsetActive",
  OpenEditLocator = "OpenEditLocator",
  RestoreElement = "RestoreElement",
  RerunGeneration = "RerunGeneration",
  StartCollectData = "StartCollectData",
  StopGroupGeneration = "StopGroupGeneration",
  ToggleElementGroup = "ToggleElementGroup",

}
