import { ElementClass } from "../../locators/types/generationClasses.types";
import { VuetifyClasses } from "../../locators/types/vuetifyClasses.types";

export const vuetifyDefaultFilterOn: ElementClass[] = [
  VuetifyClasses.alert,
  VuetifyClasses.bottomnavigation,
  VuetifyClasses.bottomsheet,
  VuetifyClasses.button,
  VuetifyClasses.calendar,
  VuetifyClasses.card,
  VuetifyClasses.carousel,
  VuetifyClasses.checkbox,
  VuetifyClasses.combobox,
  VuetifyClasses.dataIterator,
  VuetifyClasses.dataTable,
  VuetifyClasses.datePicker,
  VuetifyClasses.datePickerMonth,
  VuetifyClasses.dialog,
  VuetifyClasses.icon,
  VuetifyClasses.input,
  VuetifyClasses.list,
  VuetifyClasses.menu,
  VuetifyClasses.pagination,
  VuetifyClasses.radiobutton,
  VuetifyClasses.rangeSlider,
  VuetifyClasses.toolbar,
  VuetifyClasses.select,
  VuetifyClasses.simpleTable,
  VuetifyClasses.slider,
  VuetifyClasses.switch,
  VuetifyClasses.textfield,
  VuetifyClasses.timepicker,
  VuetifyClasses.tooltip,
];
